#!/bin/bash

# Configure Verifier for Hub Chain
# 
# This script creates the verifier config file from scratch with Hub Chain addresses.
# No sed - just generate the complete file.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"
source "$SCRIPT_DIR/../util_mvm.sh"

# Setup project root and logging
setup_project_root
setup_logging "configure-verifier-hub"
cd "$PROJECT_ROOT"

log_and_echo "✅ Configuring verifier for Hub Chain..."
log_and_echo ""

# Extract deployed address from aptos profile
CHAIN1_ADDRESS=$(get_profile_address "intent-account-chain1")

if [ -z "$CHAIN1_ADDRESS" ]; then
    log_and_echo "❌ ERROR: Could not extract Chain 1 deployed module address"
    exit 1
fi

log_and_echo "   Chain 1 deployer: $CHAIN1_ADDRESS"

# Get Requester and Solver addresses
REQUESTER_CHAIN1_ADDRESS=$(get_profile_address "requester-chain1")
SOLVER_CHAIN1_ADDRESS=$(get_profile_address "solver-chain1")

# Generate fresh ephemeral keys
generate_verifier_keys

# Create config file path
VERIFIER_E2E_CI_TESTING_CONFIG="$PROJECT_ROOT/trusted-verifier/config/verifier-e2e-ci-testing.toml"

# Generate the complete config file from scratch
cat > "$VERIFIER_E2E_CI_TESTING_CONFIG" << EOF
# Verifier E2E Testing Configuration
# Auto-generated by configure-verifier.sh - DO NOT EDIT MANUALLY

[hub_chain]
name = "Hub Chain"
rpc_url = "http://127.0.0.1:8080"
chain_id = 1
intent_module_addr = "0x$CHAIN1_ADDRESS"

[verifier]
private_key_env = "E2E_VERIFIER_PRIVATE_KEY"
public_key_env = "E2E_VERIFIER_PUBLIC_KEY"
polling_interval_ms = 2000
validation_timeout_ms = 30000

[api]
host = "127.0.0.1"
port = 3333
cors_origins = ["http://localhost:3333"]
EOF

export VERIFIER_CONFIG_PATH="$VERIFIER_E2E_CI_TESTING_CONFIG"

log_and_echo "✅ Created verifier-e2e-ci-testing.toml with Hub Chain addresses"
log_and_echo ""

