#!/bin/bash

# Run Verifier Rust Integration Tests
# 
# This script runs the Rust integration tests for the trusted verifier.
# It creates a temporary test entry point and runs cargo test.

set -e

# Get the project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
cd "$PROJECT_ROOT"

echo "📋 Running verifier Rust integration tests..."
echo ""

# Create a temporary integration test entry point
INTEGRATION_TEST_FILE="trusted-verifier/tests/integration_test_e2e.rs"
cat > "$INTEGRATION_TEST_FILE" << 'EOF'
//! E2E Integration tests entry point
//!
//! This file is temporarily generated by verifier-rust-integration-tests.sh to load e2e tests.

#[path = "../../testing-infra/e2e-tests-apt/integration-tests/mod.rs"]
mod integration;
EOF

# Run the tests from trusted-verifier directory
cd trusted-verifier
cargo test --test integration_test_e2e

# Clean up temporary test file
cd ..
rm -f "$INTEGRATION_TEST_FILE"

echo ""
echo "✅ Verifier Rust integration tests completed!"

