base:
  data_dir: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/data/maptos
  role: validator
  waypoint:
    from_file: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/data/waypoint.txt
consensus:
  vote_back_pressure_limit: 50
  safety_rules:
    service:
      type: local
    backend:
      type: on_disk_storage
      path: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/data/secure-data.json
      namespace: null
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/data/waypoint.txt
        identity_blob_path: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/validator-identity.yaml

execution:
  genesis_file_location: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/data/genesis.blob
storage:
  backup_service_address: 0.0.0.0:6186
  rocksdb_configs:
    enable_storage_sharding: false
validator_network:
  discovery_method: none
  mutual_authentication: true
  identity:
    type: from_file
    path: /Users/ap/code/movement/_research/intent-framework/infra/single-validator/work/validator-identity.yaml
  listen_address: /ip4/0.0.0.0/tcp/6180
api:
  enabled: true
  address: 0.0.0.0:8080
admin_service:
  enabled: true
  address: 0.0.0.0
  port: 9102
state_sync:
  state_sync_driver:
    bootstrapping_mode: ExecuteOrApplyFromGenesis
    continuous_syncing_mode: ExecuteTransactionsOrApplyOutputs
    enable_auto_bootstrapping: true
    max_connection_deadline_secs: 1

