#!/bin/bash

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"
source "$SCRIPT_DIR/../util_mvm.sh"

# Setup project root and logging
setup_project_root
setup_logging "submit-outflow-hub-intent"
cd "$PROJECT_ROOT"

# Verify services are running before proceeding
verify_verifier_running
verify_solver_running
verify_solver_registered

# ============================================================================
# SECTION 1: LOAD DEPENDENCIES
# ============================================================================
# Generate a random intent_id for the outflow intent
INTENT_ID="0x$(openssl rand -hex 32)"

# ============================================================================
# SECTION 2: GET ADDRESSES AND CONFIGURATION
# ============================================================================
CONNECTED_CHAIN_ID=2
CHAIN1_ADDRESS=$(get_profile_address "intent-account-chain1")
CHAIN2_ADDRESS=$(get_profile_address "intent-account-chain2")
TEST_TOKENS_CHAIN1=$(get_profile_address "test-tokens-chain1")
TEST_TOKENS_CHAIN2=$(get_profile_address "test-tokens-chain2")
REQUESTER_CHAIN1_ADDRESS=$(get_profile_address "requester-chain1")
SOLVER_CHAIN1_ADDRESS=$(get_profile_address "solver-chain1")
REQUESTER_CHAIN2_ADDRESS=$(get_profile_address "requester-chain2")
SOLVER_CHAIN2_ADDRESS=$(get_profile_address "solver-chain2")

log ""
log "📋 Chain Information:"
log "   Hub Chain Module Address (Chain 1):     $CHAIN1_ADDRESS"
log "   Connected Chain Module Address (Chain 2): $CHAIN2_ADDRESS"
log "   Requester Chain 1 (hub):     $REQUESTER_CHAIN1_ADDRESS"
log "   Solver Chain 1 (hub):       $SOLVER_CHAIN1_ADDRESS"
log "   Requester Chain 2 (connected): $REQUESTER_CHAIN2_ADDRESS"
log "   Solver Chain 2 (connected): $SOLVER_CHAIN2_ADDRESS"

# Load verifier keys (generated by deploy-contract.sh)
load_verifier_keys

# Get public key from environment variable
VERIFIER_PUBLIC_KEY_B64="${E2E_VERIFIER_PUBLIC_KEY}"

if [ -z "$VERIFIER_PUBLIC_KEY_B64" ]; then
    log_and_echo "❌ ERROR: E2E_VERIFIER_PUBLIC_KEY environment variable not set"
    log_and_echo "   The verifier public key is required for outflow intent creation."
    log_and_echo "   Please ensure E2E_VERIFIER_PUBLIC_KEY is set (generate_verifier_keys should do this)."
    exit 1
fi

VERIFIER_PUBLIC_KEY_HEX=$(echo "$VERIFIER_PUBLIC_KEY_B64" | base64 -d 2>/dev/null | xxd -p -c 1000 | tr -d '\n')

if [ -z "$VERIFIER_PUBLIC_KEY_HEX" ] || [ ${#VERIFIER_PUBLIC_KEY_HEX} -ne 64 ]; then
    log_and_echo "❌ ERROR: Invalid public key format"
    log_and_echo "   Expected: base64-encoded 32-byte Ed25519 public key"
    log_and_echo "   Got: $VERIFIER_PUBLIC_KEY_B64"
    log_and_echo "   Please ensure E2E_VERIFIER_PUBLIC_KEY is valid base64 and decodes to 32 bytes (64 hex chars)."
    exit 1
fi

VERIFIER_PUBLIC_KEY="0x${VERIFIER_PUBLIC_KEY_HEX}"
EXPIRY_TIME=$(date -d "+1 hour" +%s)
# Token amounts: 1 USDhub / 1 USDcon (6 decimals = 1_000_000)
OFFERED_AMOUNT="1000000"  # 1 USDhub = 1_000_000 (6 decimals, on hub chain)
DESIRED_AMOUNT="1000000"  # 1 USDcon = 1_000_000 (6 decimals, on connected MVM chain)
HUB_CHAIN_ID=1
EVM_ADDRESS="0x0000000000000000000000000000000000000001"

log ""
log "🔑 Configuration:"
log "   Intent ID: $INTENT_ID"
log "   Expiry time: $EXPIRY_TIME"
log "   Verifier public key: $VERIFIER_PUBLIC_KEY"
log "   Offered amount: $OFFERED_AMOUNT (1 USDhub on hub chain)"
log "   Desired amount: $DESIRED_AMOUNT (1 USDcon on connected MVM chain)"

# Get test tokens addresses from profiles
TEST_TOKENS_CHAIN1=$(get_profile_address "test-tokens-chain1")
TEST_TOKENS_CHAIN2=$(get_profile_address "test-tokens-chain2")

log ""
log "   - Getting USD token metadata addresses..."
log "     Getting USDhub metadata on Chain 1..."
USDHUB_METADATA_CHAIN1=$(get_usdxyz_metadata "0x$TEST_TOKENS_CHAIN1" "1")
log "     ✅ Got USDhub metadata on Chain 1: $USDHUB_METADATA_CHAIN1"
OFFERED_METADATA_CHAIN1="$USDHUB_METADATA_CHAIN1"

log "     Getting USDcon metadata on Chain 2..."
USDCON_METADATA_CHAIN2=$(get_usdxyz_metadata "0x$TEST_TOKENS_CHAIN2" "2")
log "     ✅ Got USDcon metadata on Chain 2: $USDCON_METADATA_CHAIN2"
DESIRED_METADATA_CHAIN2="$USDCON_METADATA_CHAIN2"

# ============================================================================
# SECTION 3: DISPLAY INITIAL STATE
# ============================================================================
log ""
display_balances_hub "0x$TEST_TOKENS_CHAIN1"
display_balances_connected_mvm "0x$TEST_TOKENS_CHAIN2"
log_and_echo ""

# ============================================================================
# SECTION 4: VERIFIER-BASED NEGOTIATION ROUTING
# ============================================================================
log ""
log "🔄 Starting verifier-based negotiation routing..."
log "   Flow: Requester → Verifier → Solver → Verifier → Requester"

# Step 1: Requester submits draft intent to verifier
log ""
log "   Step 1: Requester submits draft intent to verifier..."
DRAFT_DATA=$(build_draft_data \
    "$OFFERED_METADATA_CHAIN1" \
    "$OFFERED_AMOUNT" \
    "$HUB_CHAIN_ID" \
    "$DESIRED_METADATA_CHAIN2" \
    "$DESIRED_AMOUNT" \
    "$CONNECTED_CHAIN_ID" \
    "$EXPIRY_TIME" \
    "$INTENT_ID" \
    "$REQUESTER_CHAIN1_ADDRESS" \
    "{\"chain_addr\": \"$CHAIN1_ADDRESS\", \"flow_type\": \"outflow\", \"requester_addr_connected_chain\": \"$REQUESTER_CHAIN2_ADDRESS\"}")

DRAFT_ID=$(submit_draft_intent "$REQUESTER_CHAIN1_ADDRESS" "$DRAFT_DATA" "$EXPIRY_TIME")
log "     Draft ID: $DRAFT_ID"

# Step 2: Wait for solver service to sign the draft (polls automatically)
# The solver service running in the background will:
# - Poll for pending drafts
# - Evaluate acceptance criteria
# - Generate signature
# - Submit signature to verifier (FCFS)
log ""
log "   Step 2: Waiting for solver service to sign draft..."
log "     (Solver service polls verifier automatically)"

# Poll for signature with retry logic (solver service needs time to process)
SIGNATURE_DATA=$(poll_for_signature "$DRAFT_ID" 10 2)
RETRIEVED_SIGNATURE=$(echo "$SIGNATURE_DATA" | jq -r '.signature')
RETRIEVED_SOLVER=$(echo "$SIGNATURE_DATA" | jq -r '.solver_addr')

if [ -z "$RETRIEVED_SIGNATURE" ] || [ "$RETRIEVED_SIGNATURE" = "null" ]; then
    log_and_echo "❌ ERROR: Failed to retrieve signature from verifier"
    log_and_echo ""
    log_and_echo "🔍 Diagnostics:"
    
    # Check if solver is running
    SOLVER_LOG_FILE="$PROJECT_ROOT/.tmp/e2e-tests/solver.log"
    if [ -f "$PROJECT_ROOT/.tmp/e2e-tests/solver.pid" ]; then
        SOLVER_PID=$(cat "$PROJECT_ROOT/.tmp/e2e-tests/solver.pid")
        if ps -p "$SOLVER_PID" > /dev/null 2>&1; then
            log_and_echo "   ✅ Solver process is running (PID: $SOLVER_PID)"
        else
            log_and_echo "   ❌ Solver process is NOT running (PID: $SOLVER_PID)"
        fi
    else
        log_and_echo "   ❌ Solver PID file not found"
    fi
    
    # Show solver log
    if [ -f "$SOLVER_LOG_FILE" ]; then
        log_and_echo ""
        log_and_echo "   📋 Solver log (last 100 lines):"
        log_and_echo "   ----------------------------------------"
        tail -100 "$SOLVER_LOG_FILE" | while read line; do log_and_echo "   $line"; done
        log_and_echo "   ----------------------------------------"
    else
        log_and_echo "   ⚠️  Solver log file not found: $SOLVER_LOG_FILE"
    fi
    
    # Show verifier log
    VERIFIER_LOG_FILE="$PROJECT_ROOT/.tmp/e2e-tests/verifier.log"
    if [ -f "$VERIFIER_LOG_FILE" ]; then
        log_and_echo ""
        log_and_echo "   📋 Verifier log (last 30 lines):"
        log_and_echo "   ----------------------------------------"
        tail -30 "$VERIFIER_LOG_FILE" | while read line; do log_and_echo "   $line"; done
        log_and_echo "   ----------------------------------------"
    fi
    
    exit 1
fi
log "     ✅ Retrieved signature from solver: $RETRIEVED_SOLVER"
log "     Signature: ${RETRIEVED_SIGNATURE:0:20}..."

# ============================================================================
# SECTION 5: CREATE OUTFLOW INTENT ON-CHAIN WITH RETRIEVED SIGNATURE
# ============================================================================
log ""
log "   Creating outflow intent on hub chain..."
log "   - Requester locks 1 USDhub on hub chain"
log "   - Requester wants 1 USDcon on connected chain (Chain 2)"
log "     Offered metadata (hub): $OFFERED_METADATA_CHAIN1"
log "     Desired metadata (connected): $DESIRED_METADATA_CHAIN2"
log "     Solver address: $RETRIEVED_SOLVER"
log "     Requester address on connected chain: $REQUESTER_CHAIN2_ADDRESS"

SOLVER_SIGNATURE_HEX="${RETRIEVED_SIGNATURE#0x}"
VERIFIER_PUBLIC_KEY_HEX_CLEAN="${VERIFIER_PUBLIC_KEY#0x}"

aptos move run --profile requester-chain1 --assume-yes \
    --function-id "0x${CHAIN1_ADDRESS}::fa_intent_outflow::create_outflow_intent_entry" \
    --args "address:${OFFERED_METADATA_CHAIN1}" "u64:${OFFERED_AMOUNT}" "u64:${HUB_CHAIN_ID}" "address:${DESIRED_METADATA_CHAIN2}" "u64:${DESIRED_AMOUNT}" "u64:${CONNECTED_CHAIN_ID}" "u64:${EXPIRY_TIME}" "address:${INTENT_ID}" "address:${REQUESTER_CHAIN2_ADDRESS}" "hex:${VERIFIER_PUBLIC_KEY_HEX_CLEAN}" "address:${RETRIEVED_SOLVER}" "hex:${SOLVER_SIGNATURE_HEX}" >> "$LOG_FILE" 2>&1

# ============================================================================
# SECTION 6: VERIFY RESULTS
# ============================================================================
if [ $? -eq 0 ]; then
    log "     ✅ Outflow intent created on Chain 1!"

    sleep 2
    log "     - Verifying intent stored on-chain..."
    HUB_INTENT_ADDRESS=$(curl -s "http://127.0.0.1:8080/v1/accounts/${REQUESTER_CHAIN1_ADDRESS}/transactions?limit=1" | \
        jq -r '.[0].events[] | select(.type | contains("OracleLimitOrderEvent")) | .data.intent_addr' | head -n 1)

    if [ -n "$HUB_INTENT_ADDRESS" ] && [ "$HUB_INTENT_ADDRESS" != "null" ]; then
        log "     ✅ Hub outflow intent stored at: $HUB_INTENT_ADDRESS"
        log_and_echo "✅ Outflow intent created (via verifier negotiation)"
    else
        log_and_echo "❌ ERROR: Could not verify hub outflow intent address"
        exit 1
    fi
else
    log_and_echo "❌ Outflow intent creation failed on Chain 1!"
    log_and_echo "   Log file contents:"
    log_and_echo "   + + + + + + + + + + + + + + + + + + + +"
    cat "$LOG_FILE"
    log_and_echo "   + + + + + + + + + + + + + + + + + + + +"
    exit 1
fi

# ============================================================================
# SECTION 7: FINAL SUMMARY
# ============================================================================
log ""
display_balances_hub "0x$TEST_TOKENS_CHAIN1"
display_balances_connected_mvm "0x$TEST_TOKENS_CHAIN2"
log_and_echo ""

log ""
log "🎉 OUTFLOW - HUB CHAIN INTENT CREATION COMPLETE!"
log "================================================"
log ""
log "✅ Steps completed successfully (via verifier-based negotiation):"
log "   1. Solver registered on-chain"
log "   2. Requester submitted draft intent to verifier"
log "   3. Solver service signed draft automatically (FCFS)"
log "   4. Requester polled verifier and retrieved signature"
log "   5. Requester created outflow intent on-chain with retrieved signature"
log "   6. Tokens locked on hub chain"
log ""
log "📋 Request-intent Details:"
log "   Intent ID: $INTENT_ID"
log "   Draft ID: $DRAFT_ID"
log "   Solver: $RETRIEVED_SOLVER"
if [ -n "$HUB_INTENT_ADDRESS" ] && [ "$HUB_INTENT_ADDRESS" != "null" ]; then
    log "   Chain 1 Hub Outflow Request-intent: $HUB_INTENT_ADDRESS"
fi
log "   Requester address on connected chain: $REQUESTER_CHAIN2_ADDRESS"

save_intent_info "$INTENT_ID" "$HUB_INTENT_ADDRESS"
