#!/bin/bash

# Run Verifier Rust Integration Tests
# 
# This script runs the Rust integration tests for the trusted verifier.
# It creates a temporary test entry point and runs cargo test.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"

# Setup project root and logging
setup_project_root
setup_logging "verifier-rust-integration-tests"
cd "$PROJECT_ROOT"

# Ensure verifier config path matches the E2E config generated by configure-verifier scripts
VERIFIER_CONFIG_PATH="$PROJECT_ROOT/trusted-verifier/config/verifier-e2e-ci-testing.toml"
if [ ! -f "$VERIFIER_CONFIG_PATH" ]; then
    log_and_echo "❌ PANIC: Verifier config not found at $VERIFIER_CONFIG_PATH"
    log_and_echo "   Make sure chain-hub/configure-verifier.sh and chain-connected-mvm/configure-verifier.sh have run."
    exit 1
fi
export VERIFIER_CONFIG_PATH

# Load verifier keys (generated during deployment)
load_verifier_keys


# Create a temporary integration test entry point
INTEGRATION_TEST_FILE="trusted-verifier/tests/integration_test_e2e.rs"
cat > "$INTEGRATION_TEST_FILE" << 'EOF'
//! E2E Integration tests entry point
//!
//! This file is temporarily generated by verifier-rust-integration-tests.sh to load e2e tests.

#[path = "../../testing-infra/ci-e2e/e2e-tests-mvm/verifier-rust-integration-tests/mod.rs"]
mod integration;
EOF

# Run the tests from trusted-verifier directory
cd trusted-verifier
cargo test --test integration_test_e2e

# Clean up temporary test file
cd ..
rm -f "$INTEGRATION_TEST_FILE"


