#!/bin/bash

# Run Verifier Rust Integration Tests
# 
# This script runs the Rust integration tests for the trusted verifier.
# It creates a temporary test entry point and runs cargo test.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"

# Setup project root
setup_project_root
cd "$PROJECT_ROOT"

# Set VERIFIER_CONFIG_PATH to use verifier_testing.toml for tests
VERIFIER_TESTING_CONFIG="$PROJECT_ROOT/trusted-verifier/config/verifier_testing.toml"
export VERIFIER_CONFIG_PATH="$VERIFIER_TESTING_CONFIG"


# Create a temporary integration test entry point
INTEGRATION_TEST_FILE="trusted-verifier/tests/integration_test_e2e.rs"
cat > "$INTEGRATION_TEST_FILE" << 'EOF'
//! E2E Integration tests entry point
//!
//! This file is temporarily generated by verifier-rust-integration-tests.sh to load e2e tests.

#[path = "../../testing-infra/ci-e2e/e2e-tests-mvm/verifier-rust-integration-tests/mod.rs"]
mod integration;
EOF

# Run the tests from trusted-verifier directory
cd trusted-verifier
cargo test --test integration_test_e2e

# Clean up temporary test file
cd ..
rm -f "$INTEGRATION_TEST_FILE"


