[package]
name = "test-tokens"
version = "1.0.0"
authors = []

[addresses]
test_tokens = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "d71b74a45a52d41ef03c3e4b0ec927c14f392c05"
subdir = "aptos-move/framework/aptos-framework"

